name: Initialize Monorepo
description: Initialize nx monorepo for CI workflows

runs:
  using: 'composite'
  steps:
    - name: Use PNPM 10.x
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Update NPM
      shell: bash
      run: npm i -g npm@11.6.1
    - name: Install Node.js Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile --prefer-offline
    - name: Set git identity
      shell: bash
      run: |-
        git config user.name "release"
        git config user.email "release@github.com"
    - uses: nrwl/nx-set-shas@v4
